=== skissane/tn5250/tn5250web/tn5250.dtd
<!--
  DTD for tn5250 web pages source.
  This code is placed in the public domain.
-->

<!-- Character entities from XHTML. -->

<!ENTITY % HTMLlat1 PUBLIC
   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
   "/usr/lib/sgml/dtd/xhtml-1.1/xhtml-lat1.ent">
%HTMLlat1;

<!ENTITY % HTMLsymbol PUBLIC
   "-//W3C//ENTITIES Symbols for XHTML//EN"
   "/usr/lib/sgml/dtd/xhtml-1.1/xhtml-symbol.ent">
%HTMLsymbol;

<!ENTITY % HTMLspecial PUBLIC
   "-//W3C//ENTITIES Special for XHTML//EN"
   "/usr/lib/sgml/dtd/xhtml-1.1/xhtml-special.ent">
%HTMLspecial;


<!-- Entity definitions. -->

<!ENTITY % IdAttr "id ID #IMPLIED">

<!ENTITY % Inline "#PCDATA|kbd|var|em|strong|a|rfc|ibmbook">

<!-- Document structure. -->

<!ELEMENT webpage (head, body)>
<!ATTLIST webpage
	xml:lang	CDATA		#IMPLIED>

<!ELEMENT head (title, docuri?, trail*)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT docuri (#PCDATA)>

<!ELEMENT trail (#PCDATA)>
<!ATTLIST trail
	href		CDATA		#REQUIRED>

<!ELEMENT body (h1|h2|h3|p|dl|ul|ol|pre)*>

<!ELEMENT h1 (%Inline;)*>
<!ATTLIST h1 %IdAttr;>

<!ELEMENT h2 (%Inline;)*>
<!ATTLIST h2 %IdAttr;>

<!ELEMENT h3 (%Inline;)*>
<!ATTLIST h3 %IdAttr;>

<!ELEMENT dl (dt,dd)*>

<!ELEMENT dt (%Inline;)*>
<!ELEMENT dd (%Inline;)*>

<!ELEMENT p (%Inline;)*>

<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT li (%Inline;)*>

<!ELEMENT pre (%Inline;)*>
<!ATTLIST pre
	xml:space	(preserve|default)	"preserve">

<!ELEMENT kbd (%Inline;)*>
<!ELEMENT var (%Inline;)*>
<!ELEMENT em (%Inline;)*>
<!ELEMENT strong (%Inline;)*>

<!ELEMENT a (%Inline;)*>
<!ATTLIST a
	%IdAttr;
	href		CDATA		#REQUIRED
	title		CDATA		#IMPLIED>

<!ELEMENT rfc EMPTY>
<!ATTLIST rfc
	number		CDATA		#REQUIRED>

<!ELEMENT ibmbook EMPTY>
<!ATTLIST ibmbook
	code		CDATA		#REQUIRED
	pubnum		CDATA		#REQUIRED>

=== skissane/tn5250/tn5250web/index.xml
<?xml version="1.0"?>

<!DOCTYPE webpage SYSTEM "tn5250.dtd">

<?xml-stylesheet href="tn5250.xsl" type="text/xml"?>

<webpage xml:lang="en">
  <head>
    <title>tn5250</title>
    <docuri>http%3A%2F%2Ftn5250.sourceforge.net%2F</docuri>
  </head>

  <body>
    <h1>tn5250</h1>

    <p>This is the homepage for the free tn5250 emulator.  It’s
      sometimes described as “Linux tn5250”, although it
      works on FreeBSD and any other modern Unix.</p>

    <p>tn5250 is a telnet client for the
<a href="http://www.iseries.ibm.com/">IBM AS/400</a> that emulates
      5250 terminals and printers.  This function is the same as that
      provided by the 5250 emulator in IBM Client Access.</p>

    <p>The tn5250 project is kindly hosted by
      <a href="http://sourceforge.net/">SourceForge</a>.  Thanks!</p>


    <h2>People</h2>

    <p><a href="http://www.linux-sna.org/software/5250/">Michael
	Madore</a> is the principal author of tn5250 — he got the
      whole thing going.</p>

    <p><a href="http://www.nacs.net/~jasonf/">Jay Felice</a> has done
      a lot of good work on tn5250 as well, and provided the CVS
      server and download site for a few years.</p>

    <p>Scott Klement has gotten himself into the ChangeLog a bit,
      too.</p>

    <p><a href="http://home.clear.net.nz/pages/c.evans/">Carey
	Evans</a>, your humble narrator, hasn’t done much; he
      contributed the initial
      <a href="http://www.gnu.org/software/automake/automake.html">automake</a>
      support and left it for Michael and Jay to get working, wrote
      the man pages, and got the project set up on
      SourceForge.</p>

    <p>Many others have contributed
      <a href="http://sourceforge.net/tracker/?group_id=27533&amp;atid=390791">bug reports</a>,
      <a href="http://sourceforge.net/tracker/?group_id=27533&amp;atid=390794">feature requests</a>,
      <a href="http://sourceforge.net/tracker/?group_id=27533&amp;atid=390793">patches</a>
      and suggestions.  Thanks to you all!</p>


<h2>Users</h2>

<p>The source for the latest stable version of tn5250 should be
able to be downloaded from the
<a href="http://sourceforge.net/project/showfiles.php?group_id=27533">Sourceforge
files page</a>.  <a href="http://www.debian.org/">Debian</a>
users can install it via apt: <kbd>apt-get install
tn5250</kbd>.  RedHat users can download
<a href="ftp://ftp.falsehope.com/home/gomez/tn5250/">RPMs
prepared by Henri Gomez</a>.</p>

<p>Discussion about tn5250 takes place on the
<a href="http://www.midrange.com/linux5250.shtml">LINUX5250
mailing list</a>, which is located at
<a href="http://www.midrange.com/">MIDRANGE dot COM</a>.
The <a href="http://archive.midrange.com/linux5250/index.htm">mailing
list archives</a> are also available there.</p>

<p>You can report bugs and send patches to the mailing list, or use the
<a href="http://sourceforge.net/tracker/?group_id=27533">SourceForge
Trackers</a> on the
<a href="http://sourceforge.net/projects/tn5250/">tn5250
project pages</a>.</p>

<p>There is also a
<a href="http://perso.libertysurf.fr/plinux/tn5250-faq.html">tn5250
FAQ</a> available.  It’s a little out of date, but still
contains useful information.</p>


<h2>Developers</h2>

<p>As well as the resources for users listed above, the
CVS repository is hosted on SourceForge.  See the
<a href="http://sourceforge.net/cvs/?group_id=27533">tn5250
CVS page</a>.</p>

<p>There’s also a page of <a href="resources.html">links to
related documentation</a> at this site.</p>


<h2>Related Free Software</h2>

<p><a href="http://tn5250j.sourceforge.net/">tn5250j</a> is a 5250
emulator written in Java.</p>

<p><a href="http://www.geocities.com/SiliconValley/Peaks/7814/">x3270</a>
implements the tn3270 protocol, which is very similar to tn5250.</p>

</body>
</webpage>

=== skissane/tn5250/tn5250web/resources.xml
<?xml version="1.0"?>

<!DOCTYPE webpage SYSTEM "tn5250.dtd">

<?xml-stylesheet href="tn5250.xsl" type="text/xml"?>

<webpage xml:lang="en">
  <head>
    <title>Developer Resources</title>
    <trail href="./">tn5250</trail>
  </head>

  <body>
    <h1>tn5250 Developer Resources</h1>

    <h2 id="ietf">IETF</h2>

    <p>The
      <a href="http://www.ietf.org/html.charters/OLD/tn3270e-charter.html">IETF
        tn3270e Working Group</a> defined standards for 3270 and
      5250 over TCP/IP.  These standards make use of the existing
      Telnet standards.</p>

    <dl>
      <dt><rfc number="854"/></dt>
      <dd>Telnet Protocol Specification</dd>

      <dt><rfc number="855"/></dt>
      <dd>Telnet Option Specifications</dd>

      <dt><rfc number="856"/></dt>
      <dd>Telnet Binary Transmission</dd>

      <dt><rfc number="860"/></dt>
      <dd>Telnet Timing Mark Option</dd>

      <dt><rfc number="885"/></dt>
      <dd>Telnet End Of Record Option</dd>

      <dt><rfc number="1091"/></dt>
      <dd>Telnet Terminal-Type Option</dd>

      <dt><rfc number="1205"/></dt>
      <dd>5250 Telnet Interface</dd>

      <dt><rfc number="1572"/></dt>
      <dd>Telnet Environment Option</dd>

      <dt><rfc number="2877"/></dt>
      <dd>5250 Telnet Enhancements.  This standard extends RFC 1205
	and includes a useful list of references in section 13.</dd>
    </dl>

    <h2 id="ibm">IBM</h2>

    <p>These documents are available online from IBM and include
      information relevant to the tn5250 project.</p>

    <dl>
      <dt><ibmbook code="CO2E2001" pubnum="SC30-3533-03"/></dt>
      <dd>5494 Remote Control Unit, Functions Reference.</dd>

      <dt><ibmbook code="CO2A2002" pubnum="GA27-3960-05"/></dt>
      <dd>5494 Remote Control Unit, Userâ€™s Guide.</dd>

      <dt><ibmbook code="QB3AQ501" pubnum="SC41-5603-01"/></dt>
      <dd>AS/400 International Application Development V4R2.
	Appendices A and F describe the EBCDIC and ASCII character
	sets that the AS/400 supports.</dd>

      <dt><ibmbook code="QB3AWC01" pubnum="SC41-5101-01"/></dt>
      <dd>AS/400 National Language Support V4R2.  Further information
	about character sets, especially as it relates to display
	devices.</dd>

      <dt><ibmbook code="FOCREF00" pubnum="SC09-2190-01"/></dt>
      <dd>CDRA Reference.  Even more information about how character
	sets work on the AS/400, and how conversion between them
	should work.</dd>

      <dt><ibmbook code="QB3ANB00" pubnum="SC41-5401-00"/></dt>
      <dd>OS/400 Communications Configuration V4R1.  Chapter 8 defines
	the parameters that may be passed to the AS/400 over the
	telnet connection to configure the display or printer device.</dd>

      <dt><a href="pwsubciw.zip">PWSUBS</a> (Zip file)</dt>
      <dd>APPC Password Substitution.  This describes the scheme used
        for automatic signon, which is currently unimplemented in tn5250.</dd>
    </dl>
  </body>
</webpage>
